# Generated by Django 4.2 on 2023-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '__first__'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='chosen_tag', to='tags.tags'),
        ),
    ]
