# Generated by Django 4.2.1 on 2023-05-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='performer',
            new_name='executor',
        ),
    ]
